### ISSUE TITLE
Use React-i18next for internationalization

### ISSUE THREAD

**Issue by deloreyj** [jedmao/tsx#10]
I want to propose using [React-18next](https://react.i18next.com/guides/quick-start) for internationalization as opposed to React-Intl. This document will lay out a few justifications for that opinion. This document is not exhaustive, but intends to be a starting point for a deeper conversation.

### Benefits
First, I believe that it has at least feature parity with react-intl in terms of important features like [formatting dates and numbers](https://www.i18next.com/translation-function/formatting#formatting), [pluralization](https://www.i18next.com/translation-function/plurals), [SSR support](https://react.i18next.com/latest/ssr), etc.

Second, react-i18next has a number of options of ways to translate strings including [useTranslation (hook)](https://react.i18next.com/latest/usetranslation-hook), [withTranslation (HOC)](https://react.i18next.com/latest/withtranslation-hoc), [Translation (render prop)](https://react.i18next.com/latest/translation-render-prop), and a [Trans wrapper component that can handle blocks of JSX](https://react.i18next.com/latest/trans-component). I'm particularly excited about a translation component that can gracefully handle blocks of jsx for instances when a single string does not convey the full context of the message. 

Each of these methods allow the full strings to remain co-located with the component they're used in as opposed to the approach currently used in the google sales client which relies solely on ids to pull in translations at runtime (see below). The current approach in the google sales client makes reading the code tedious and eliminates the ability for developers to search for strings they see in the UI to find the corresponding React code.

![image](https://user-images.githubusercontent.com/6365144/56695877-644f4900-66a7-11e9-8969-cef93066f378.png)

Third, react-i18next provides multiple methods of [string extraction](https://react.i18next.com/guides/extracting-translations) including manual addition, parsing libraries, or a runtime extraction method that uses an express endpoint to automatically add unrecognized strings to string files. 

Fourth, react-18next supports [multiple translation files](https://react.i18next.com/guides/multiple-translation-files) which means that not all the strings need to be loaded on the initial page load. We can namespace translations and the all of the hook, higher order component, and render prop will automatically Suspense until translations are loaded. This will prevent negatively affecting initial page load as our translation count grows.

### Drawbacks
1) Larger dependency size. i18next is 33kb minified and 9kb gzipped. One option is to precompile translations, which brings the gzipped size to 4kb but adversely affects the size of translation files.
2) Complexity - All of the features introduce a steeper initial learning curve

**Comment by jedmao** [comment]
Tabling this idea for now. It looks like the CRA team is a bit open to react-intl ATM, so let's wait and see where this goes.
